name = "cf_ai_resume_coach"
main = "src/worker.ts"
compatibility_date = "2025-10-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]

[assets]
directory = "public"
