name = "cf_ai_resume_coach"
main = "src/worker.ts"
compatibility_date = "2025-10-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionDO"

[[migrations]]
tag = "v2"                         # <— bump this each time you change migrations
new_sqlite_classes = ["SessionDO"] # <— required for free plan Durable Objects

[assets]
directory = "public"
